config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "communities#index"
  resources :users

  resources :communities do
    resource :follows, only: [:create, :destroy]
  end

  resources :mypage, only: [:profile] do
    member do
      get 'profile'
      get 'posted_community'
      get 'following_community'
    end
  end


  # get 'rooms_personal/index' => 'rooms_personal#index'
  get 'rooms_personal/show' => 'rooms_personal#show'
  # get 'rooms_personal/create' => 'rooms_personal#create'

  resources :messages, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  attachment :intro_image
  has_many :follows, dependent: :destroy

  # belongs_to :room


  with_options if: :published? do
    validates :title, presence: true
    validates :introduction, presence: true
   # 複数valitatesをまとめたい場合はwith_optionsを使用（published?はメソッド名またはmodelのboolean項目)
 end

  def published?
    false
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
  # belongs_to :user
  # belongs_to :room
  # validates :room_id, uniqueness: { scope: :user_id }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates_uniqueness_of :community_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord
  
end

app/models/room.rb
class Room < ApplicationRecord
  # has_many :messages
  # has_many :entries
  # has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image_id
  has_many :communities, dependent: :destroy
  has_many :follows, dependent: :destroy

  # belongs_to:entry
  # has_many:message

  def following?(community)
    self.follows.exists?(community_id: community.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  before_action :set_community, only: [:edit, :show, :update]

    def new
      @community = Community.new
    end

    def create
      @community = current_user.communities.build(community_params)#ストロングパラメータを呼び出す
      if @community.save
        redirect_to communities_path(@community), notice: "投稿に成功しました。"
      else
        render :new
      end
    end


    def edit
      if @community.user_id != current_user.id
        redirect_to communities_path, alert: '不正なアクセスです。'
      end
      @community = Community.find(params[:id])
      
    end

    def index
      @communities = Community.all
    end

    def show


    end

    def update
      if @community.update(community_params)
         redirect_to communities_path(@community), notice: "投稿に成功しました。"
      else
        render :edit
      end
    end

    def destroy
      community = Community.find(params[:id])
      community.destroy
      redirect_to communities_path
    end

    private
    def  community_params
      params.require(:community).permit(:title, :introduction, :intro_image)#ストロングパラメータを定義
    end

    def set_community
      @community = Community.find(params[:id])
    end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController


  def create
    @follow = current_user.follows.create(community_id:params[:community_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @community = Community.find(params[:community_id])
    @follow = current_user.follows.find_by(community_id: @community.id)
    @follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create!(message_params)
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  def profile
    @user = User.find(params[:id]) #各ユーザアカウントのユーザー情報を表示
  end

  def posted_community
    @communities = Community.where(user_id: current_user.id)
  end

  def following_community
    @communities = Community.where(user_id: current_user.id)
  end
end

app/controllers/rooms_group_controller.rb
class RoomsGroupController < ApplicationController
  def index
    @rooms = Room.all
  end

  def create
    @room = Room.new
    @room.save
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.recent.limit(5).reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users =　User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to profile_mypage_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :profile , :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/rooms_group_helper.rb
module RoomsGroupHelper
end

app/helpers/rooms_personal_helper.rb
module RoomsPersonalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_form.html.erb
<section>
  <div class="container">
      <div class="co_post_form">
        <%= form_for @community do |f| %>
          <div class="col">
            <div class="field">
              <%= f.label :title%>
              <%= f.text_field :title %>
            </div>

             <div class="body">
               <%= f.label :introduction ,class:"introduction"%>
               <%= f.text_area :introduction ,class:"introduction" %>
             </div>

             <div class="image">
               <%= f.label :intro_image %>
               <%= f.attachment_field :intro_image %>
             </div>

             <%= f.submit '投稿', class:"btn btn-primary btn-lg"%>
           </div>
         <%end%>
      </div>
  </div>
</section>

<style>
  section {
    text-align:center;

    padding-top:100px;
  }

 .introduction {
   weight:120px;
 }

</style>

app/views/communities/edit.html.erb
<h2>コミュニティ編集</h2>

<%= render "form" %>

app/views/communities/index.html.erb
<div class="container">
  <div class="row">
    <% @communities.each do |community| %>
      　<div class="col-md-3">
          <%= link_to community_path(community) do %>
            <div class="card mb-4 shadow-sm" style="width: 14rem;">
              <%= attachment_image_tag community, :intro_image, fallback:"no-image.jpg", class:"card-img-top" %>
               <div class="card-body">
                 <h5 class="card-title"><%= community.title %></h5>
                 <p class="card-text"><%= community.introduction%></p>
                 <div class="d-flex justify-content-between align-items-center">

                  <% if current_user.present? && current_user.following?(community) %>
                    <%= link_to  community_follows_path(community.id), method: :delete, remote: true do %>
                      <button type="button" class="btn btn-primary btn-sm">フォローを外す</button>
                    <%end%>
                  <% else %>
                    <%= link_to  community_follows_path(community.id), method: :post, remote: true do %>
                      <button type="button" class="btn btn-outline-primary btn-sm">フォロー</button>
                    <%end%>
                  <%end%>
                  <small class="text-muted"><%= community.follows.count %></small>
                </div>
              </div>
            </div>
          <%end%>
      </div>
    <%end%>
  </div>
</div>

    <style>
      .intro_image {
        width: 222px;
        height: 180px;

      }



      .row {
         padding-top: 30px;
      }

      .card {
        height:330px;

      }

    </style>

app/views/communities/new.html.erb
<h2>コミュニティ新規作成</h2>

<%= render "form" %>

app/views/communities/show.html.erb
<%= attachment_image_tag  @community, :intro_image, fallback: "no-image.jpg", class: "intro_image" %>

<%= @community.title %>

<%= simple_format @community.introduction %>

<%= @community.user.username %>

<%= link_to "編集", edit_community_path(@community), class: "btn btn-primary btn-md" %>