config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "communities#index"
  resources :users

  resources :communities do
    resource :follows, only: [:create, :destroy]
  end

  resources :mypage, only: [:profile] do
    member do
      get 'profile'
      get 'posted_community'
      get 'following_community'
    end
  end


  # get 'rooms_personal/index' => 'rooms_personal#index'
  get 'rooms_personal/show' => 'rooms_personal#show'
  # get 'rooms_personal/create' => 'rooms_personal#create'

  resources :messages, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  attachment :intro_image
  has_many :follows, dependent: :destroy

  # belongs_to :room


  with_options if: :published? do
    validates :title, presence: true
    validates :introduction, presence: true
   # 複数valitatesをまとめたい場合はwith_optionsを使用（published?はメソッド名またはmodelのboolean項目)
 end

  def published?
    false
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
  # belongs_to :user
  # belongs_to :room
  # validates :room_id, uniqueness: { scope: :user_id }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates_uniqueness_of :community_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord
  
end

app/models/room.rb
class Room < ApplicationRecord
  # has_many :messages
  # has_many :entries
  # has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image_id
  has_many :communities, dependent: :destroy
  has_many :follows, dependent: :destroy

  # belongs_to:entry
  # has_many:message

  def following?(community)
    self.follows.exists?(community_id: community.id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController


  def create
    @follow = current_user.follows.create(community_id:params[:community_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @community = Community.find(params[:community_id])
    @follow = current_user.follows.find_by(community_id: @community.id)
    @follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  def profile
    @user = User.find(params[:id]) #各ユーザアカウントのユーザー情報を表示
  end

  def posted_community
    @communities = Community.where(user_id: current_user.id)
  end

  def following_community
    @communities = Community.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users =　User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to profile_mypage_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :profile , :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/rooms_group_helper.rb
module RoomsGroupHelper
end

app/helpers/rooms_personal_helper.rb
module RoomsPersonalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>join_app_sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if flash[:notice]%>
        <div class="notification_msg">
          <p class="notice"><%= notice %></p>
        </div>
    <%end%>

    <%if flash[:alert]%>
        <div class="notification_alert">
          <p class="alert"><%= alert %></p>
        </div>
    <%end%>

      <header>
        <div class="navbar-item">
            <%= link_to root_path, class:  "navbar-item" do%>
            <h1 class="title" style="">Join2</h1>
            <%end%>
            <div class="auth_func">
              <% if user_signed_in? %>
                <%= link_to 'ログアウト',destroy_user_session_path, method: :delete %>
               <div class="user_contents">         　
                <%= link_to 'マイページ', profile_mypage_path(id: current_user) %>      　　
                <%= link_to 'コミュニティを作成する', new_community_path(id: current_user) %>
                <%= link_to '投稿したコミュニティ' , posted_community_mypage_path(id: current_user) %>
                <%= link_to 'フォローしたコミュニティ', following_community_mypage_path(id: current_user) %>
                <%# <%= link_to 'メッセージ', chat_path(id: current_user) %> 

      　　　　　</div>
            </div>
             <%else%>
                <%= link_to 'ログイン', new_user_session_path %>
                <%= link_to '新規登録', new_user_registration_path %>
          　  <%end%>
        </div>
      </header>
    <%= yield %>
  </body>
</html>

<style>
    .user_contents {
       text-align: right;
       display: flex;
       flex-direction: column;

    }
<<<<<<< HEAD
=======

>>>>>>> user_func
</style>